export const Topics = {
  UI_COMMAND: "UI.COMMAND",
  UI_TOOL_CHANGED: "UI.TOOL_CHANGED",
  UI_OBJECT_PROPERTIES_CHANGED: "UI.OBJECT_PROPERTIES_CHANGED",

  DIALOG_REQUEST: "DIALOG.REQUEST",

  VIEWPORT_PAN_CHANGED: "VIEWPORT.PAN_CHANGED",
  VIEWPORT_ZOOM_CHANGED: "VIEWPORT.ZOOM_CHANGED",

  GRAPHICS_SELECTION_CHANGED: "GRAPHICS.SELECTION_CHANGED",
  GRAPHICS_SELECTION_SET_CHANGED: "GRAPHICS.SELECTION_SET_CHANGED",
  GRAPHICS_ENTITY_UPDATED: "GRAPHICS.ENTITY_UPDATED",
  GRAPHICS_RENDER_UPDATED: "GRAPHICS.RENDER_UPDATED",

  INPUT_BOX_SELECTION_START: "INPUT.BOX_SELECTION_START",
  INPUT_BOX_SELECTION_CHANGE: "INPUT.BOX_SELECTION_CHANGE",
  INPUT_BOX_SELECTION_END: "INPUT.BOX_SELECTION_END",

  INPUT_VIEWPORT_PAN_START: "INPUT.VIEWPORT_PAN_START",
  INPUT_VIEWPORT_PAN_MOVE: "INPUT.VIEWPORT_PAN_MOVE",
  INPUT_VIEWPORT_PAN_END: "INPUT.VIEWPORT_PAN_END",
  INPUT_VIEWPORT_ZOOM: "INPUT.VIEWPORT_ZOOM",

  INPUT_TRANSFORM_HANDLE_START: "INPUT.TRANSFORM_HANDLE_START",
  INPUT_TRANSFORM_HANDLE_DRAG: "INPUT.TRANSFORM_HANDLE_DRAG",
  INPUT_TRANSFORM_HANDLE_END: "INPUT.TRANSFORM_HANDLE_END",

  INPUT_MOUSE_DOWN: "INPUT.MOUSE_DOWN",
  INPUT_MOUSE_MOVE: "INPUT.MOUSE_MOVE",
  INPUT_MOUSE_UP: "INPUT.MOUSE_UP",
  INPUT_DOUBLE_CLICK: "INPUT.DOUBLE_CLICK",
  INPUT_WHEEL: "INPUT.WHEEL",
  INPUT_CONTEXT_MENU: "INPUT.CONTEXT_MENU",
  INPUT_KEY_DOWN: "INPUT.KEY_DOWN",
  INPUT_KEY_UP: "INPUT.KEY_UP",
  INPUT_CANVAS_READY: "INPUT.CANVAS_READY",
  INPUT_CANVAS_RESIZED: "INPUT.CANVAS_RESIZED",
  LOG_EVENT: "LOG.EVENT",
  RENDER_STATS: "RENDER.STATS"
} as const;
